language:
  - php
  - c

compiler:
  - gcc
  - clang

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpize && ./configure CFLAGS="-O2 -g3 -Wall -Werror" --silent && make --silent && make install

script:
  - .travis/run_php_tests.sh
  - phpenv config-add .travis/stribog.ini
  - $(phpenv which php) benchmark.php

after_failure:
  - .travis/after_failure.sh
